/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/zPJbVj35zHI
 */
import { Input } from "@/components/ui/input"
import Link from "next/link"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { Button } from "@/components/ui/button"

export function userListTable() {
  return (
    <div className="flex flex-col gap-2">
      <div className="rounded-lg border overflow-hidden shadow-lg">
        <div className="grid grid-cols-3 items-center p-4 bg-gray-100 dark:bg-gray-800">
          <h1 className="text-2xl font-bold text-gray-800 dark:text-gray-200">Users</h1>
          <form className="flex items-center gap-4">
            <SearchIcon className="h-4 w-4 text-gray-500 dark:text-gray-400" />
            <Input className="flex-1" placeholder="Search..." type="search" />
          </form>
          <Link className="flex justify-end underline text-gray-500 dark:text-gray-400" href="#">
            Export
          </Link>
        </div>
        <div className="border-t">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Name</TableHead>
                <TableHead>Email</TableHead>
                <TableHead>Role</TableHead>
                <TableHead>Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              <TableRow className="animate-fade-in">
                <TableCell className="font-semibold">Alice</TableCell>
                <TableCell>alice@example.com</TableCell>
                <TableCell>
                  <Select>
                    <SelectTrigger>
                      <SelectValue>Admin</SelectValue>
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem>Admin</SelectItem>
                      <SelectItem>User</SelectItem>
                    </SelectContent>
                  </Select>
                </TableCell>
                <TableCell>
                  <div className="flex gap-2">
                    <Button variant="outline">View</Button>
                    <Button variant="outline">Edit</Button>
                    <Button variant="outline">Delete</Button>
                  </div>
                </TableCell>
              </TableRow>
              <TableRow className="animate-fade-in">
                <TableCell className="font-semibold">Bob</TableCell>
                <TableCell>bob@example.com</TableCell>
                <TableCell>
                  <Select>
                    <SelectTrigger>
                      <SelectValue>User</SelectValue>
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem>Admin</SelectItem>
                      <SelectItem>User</SelectItem>
                    </SelectContent>
                  </Select>
                </TableCell>
                <TableCell>
                  <div className="flex gap-2">
                    <Button variant="outline">View</Button>
                    <Button variant="outline">Edit</Button>
                    <Button variant="outline">Delete</Button>
                  </div>
                </TableCell>
              </TableRow>
              <TableRow className="animate-fade-in">
                <TableCell className="font-semibold">Charlie</TableCell>
                <TableCell>charlie@example.com</TableCell>
                <TableCell>
                  <Select>
                    <SelectTrigger>
                      <SelectValue>Admin</SelectValue>
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem>Admin</SelectItem>
                      <SelectItem>User</SelectItem>
                    </SelectContent>
                  </Select>
                </TableCell>
                <TableCell>
                  <div className="flex gap-2">
                    <Button variant="outline">View</Button>
                    <Button variant="outline">Edit</Button>
                    <Button variant="outline">Delete</Button>
                  </div>
                </TableCell>
              </TableRow>
              <TableRow className="animate-fade-in">
                <TableCell className="font-semibold">David</TableCell>
                <TableCell>david@example.com</TableCell>
                <TableCell>
                  <Select>
                    <SelectTrigger>
                      <SelectValue>User</SelectValue>
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem>Admin</SelectItem>
                      <SelectItem>User</SelectItem>
                    </SelectContent>
                  </Select>
                </TableCell>
                <TableCell>
                  <div className="flex gap-2">
                    <Button variant="outline">View</Button>
                    <Button variant="outline">Edit</Button>
                    <Button variant="outline">Delete</Button>
                  </div>
                </TableCell>
              </TableRow>
              <TableRow className="animate-fade-in">
                <TableCell className="font-semibold">Eve</TableCell>
                <TableCell>eve@example.com</TableCell>
                <TableCell>
                  <Select>
                    <SelectTrigger>
                      <SelectValue>Admin</SelectValue>
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem>Admin</SelectItem>
                      <SelectItem>User</SelectItem>
                    </SelectContent>
                  </Select>
                </TableCell>
                <TableCell>
                  <div className="flex gap-2">
                    <Button variant="outline">View</Button>
                    <Button variant="outline">Edit</Button>
                    <Button variant="outline">Delete</Button>
                  </div>
                </TableCell>
              </TableRow>
            </TableBody>
          </Table>
        </div>
        <div className="flex justify-between p-4 bg-gray-100 dark:bg-gray-800">
          <div>
            <Button variant="outline">Bulk Actions</Button>
            <Button variant="outline">New User</Button>
          </div>
        </div>
      </div>
    </div>
  )
}


function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}
